apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ingress
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`argocd.local`)
    services:
    - name: argocd-server
      port: 80
  - kind: Rule
    match: Host(`argocd.local`) && PathPrefix(`/api`)
    services:
    - name: argocd-server
      port: 80
  tls:
    certResolver: default
