# Service Configuration reference
SERVICES = {
    'vburtonS' => {
        ip: '192.168.56.110',
        hostname: 'vburtonS',
    },
    'vburtonSW' => {
        ip: '192.168.56.111',
        hostname: 'vburtonSW',
    }
}

Vagrant.configure("2") do |config|

    config.vm.box = "debian/bookworm64"
    config.ssh.insert_key=false

    ssh_pub_key = File.read(File.expand_path("~/.ssh/vagrantConfig.pub"))

    config.vm.define "vburtonS" do |control|
        control.vm.hostname = SERVICES['vburtonS'][:hostname]
        control.vm.network "private_network", ip: SERVICES['vburtonS'][:ip]
        
        control.vm.provider "virtualbox" do |vb|
            vb.name = "vburtonS"
            vb.memory = 1024
            vb.cpus = 1
        end

        control.vm.provision "shell", inline: <<-SHELL
            apt-get update -y
            apt-get install -y curl ca-certificates sudo net-tools openssh-server

            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -

            cp /etc/rancher/k3s/k3s.yaml /home/vagrant/k3s.yaml
            sed -i 's/127.0.0.1/192.168.56.110/' /home/vagrant/k3s.yaml
            chown vagrant:vagrant /home/vagrant/k3s.yaml

            echo "alias k='sudo k3s kubectl'" >> /home/vagrant/.bashrc

            cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
            chmod 600 /vagrant/node-token
            chown vagrant:vagrant /vagrant/node-token
        SHELL
    end

    config.vm.define "vburtonSW" do |control|
        control.vm.hostname = SERVICES['vburtonSW'][:hostname]
        control.vm.network "private_network", ip: SERVICES['vburtonSW'][:ip]
        
        control.vm.provider "virtualbox" do |vb|
            vb.name = "vburtonSW"
            vb.memory = 512
            vb.cpus = 1
        end
        

        control.vm.provision "shell", inline: <<-SHELL
            apt-get update -y
            apt-get install -y curl ca-certificates sudo net-tools openssh-client


            export K3S_GET_TOKEN=$(cat /vagrant/node-token)
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.111" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=${K3S_GET_TOKEN} sh -

            echo "alias k='sudo k3s kubectl'" >> /home/vagrant/.bashrc
            export KUBECONFIG=/home/vagrant/k3s.yaml
        SHELL
    end
end